import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Table, Image, Button, Typography } from 'antd';
import { useDispatch } from 'react-redux';
import { useRouter } from 'next/router';

import Fixtures from '../datas/ligue1_fixtures.json';

const { Paragraph } = Typography;

export default function Home() {

  const [list, setList] = useState([]);

  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {

    const { calendar } = Fixtures;
    let finalList = [];
    for (let match of calendar) {
      if (new Date() <= new Date(match.fixture.date)) {
        finalList.push({
          home: match.teams.home,
          date: match.fixture.date,
          away: match.teams.away,
          id: match.fixture.id,
        })
      }
    };
    finalList = finalList.sort((a, b) => new Date(a.date) - new Date(b.date));
    setList(finalList)
  }, []);

  const getDate = id => {
    let index;
    for (let match of list){
      if (match.id === id) index = list.indexOf(match)
    };
    dispatch({type: 'getDate', date: list[index].date});
    router.push(`match/${id}`)
  };

  const columns = [
    {
      title: 'Home team',
      dataIndex: 'home',
      key: 'home',
      render: team => (
        <div className={styles.home}>
          <Paragraph className={styles.homeName}>{team.name}</Paragraph>
          <Image src={team.logo} width={50} />
        </div>

      )
    },
    {
      title: 'Date',
      dataIndex: 'date',
      key: 'date',
      render: date => new Date(date).toLocaleDateString()
    },
    {
      title: 'Away team',
      dataIndex: 'away',
      key: 'away',
      render: team => (
        <div className={styles.away}>
          <Image src={team.logo} width={50} />
          <Paragraph className={styles.awayName}>{team.name}</Paragraph>
        </div>

      )
    },
    {
      title: 'Bet',
      dataIndex: 'id',
      key: 'id',
      render: id => <Button type="primary" onClick={() => getDate(id)}>BET</Button>
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto-Bet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Choose your match :</h1>
      <Table dataSource={list} columns={columns} style={{ width: '50%' }} />
    </div>
  )
};
